### PR TITLE
updated Locale debugging

### PR DESCRIPTION
**Pull request by Numynum**
you accidentally undid the previous PR, so here it is again ;)
see https://github.com/cr4ckp0t/ElvUI_ChatTweaks/pull/3

### CODE REVIEW

**Comment by cr4ckp0t** [comment]
Debugging was working as intended. Curse's packager handles the locales correctly and debugging is silent for me, but "debug = true" is commented out in the final package. This would undo this effect.

**Comment by Numynum** [comment]
the debug = true is commented yes, so in the final package, the value of debug is false
that's all working beautifully

But; quoting https://github.com/cr4ckp0t/ElvUI_ChatTweaks/pull/3 :
the 4th parameter for NewLocale is the silent flag, which should be true when debug is false, and the other way around

the 4th parameter for NewLocal is not 'debug', it's 'silent'; they should be opposites
you can try deleting a locale entry, and then check the lua error handler, and you should see it logs the missing locale entry

**Comment by cr4ckp0t** [comment]
I am aware of how it is intended to be used, however, I handle the locale stuff automatically. It is done via a Python script just before I upload it to GitHub. Therefore, I would get nothing but errors if I had it set as you do. In theory, if the script is working properly then it is pulling the correct locale strings and adding them to Curse. If not, and users are seeing error messages, then they can be reported and I can see why the Python script is not working as intended.

**Comment by Numynum** [comment]
I see, so it's more like a local debugging variable, rather than preventing errors going to users
that's fine then, it's not obvious without knowing that context, that's why I thought there was a mistake :)

**Comment by cr4ckp0t** [comment]
Yeah no worries. If you are getting errors relating to the locales, then please do let me know. I can already think of one that is possibly causing an error.

**Pull request closed without merging**
